version: '2'
services:
  lenses-dev:
    image: landoop/kafka-lenses-dev
    ports:
      - "3030:3030"
      - "2181:2181"
      - "9092:9092"
      - "9093:9093"
      - "8081:8081"
    environment:
      - SAMPLEDATA=0
      - ENABLE_SSL=1
      - KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.auth.SimpleAclAuthorizer
      - KAFKA_SUPER_USERS=User:kafka;
      - KAFKA_PRINCIPAL_BUILDER_CLASS=de.thmshmm.kafka.CustomPrincipalBuilder
      - KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
      - LENSES_KAFKA_BROKERS=SSL://localhost:9093
      - LENSES_KAFKA_SETTINGS_CONSUMER_SECURITY_PROTOCOL=SSL
      - LENSES_KAFKA_SETTINGS_CONSUMER_SSL_TRUSTSTORE_LOCATION=/tmp/certs/truststore.jks
      - LENSES_KAFKA_SETTINGS_CONSUMER_SSL_TRUSTSTORE_PASSWORD=fastdata
      - LENSES_KAFKA_SETTINGS_CONSUMER_SSL_KEYSTORE_LOCATION=/tmp/certs/kafka.jks
      - LENSES_KAFKA_SETTINGS_CONSUMER_SSL_KEYSTORE_PASSWORD=fastdata
      - LENSES_KAFKA_SETTINGS_CONSUMER_SSL_KEY_PASSWORD=fastdata
      - LENSES_KAFKA_SETTINGS_PRODUCER_SECURITY_PROTOCOL=SSL
      - LENSES_KAFKA_SETTINGS_PRODUCER_SSL_TRUSTSTORE_LOCATION=/tmp/certs/truststore.jks
      - LENSES_KAFKA_SETTINGS_PRODUCER_SSL_TRUSTSTORE_PASSWORD=fastdata
      - LENSES_KAFKA_SETTINGS_PRODUCER_SSL_KEYSTORE_LOCATION=/tmp/certs/kafka.jks
      - LENSES_KAFKA_SETTINGS_PRODUCER_SSL_KEYSTORE_PASSWORD=fastdata
      - LENSES_KAFKA_SETTINGS_PRODUCER_SSL_KEY_PASSWORD=fastdata
      - EULA=https://dl.lenses.stream/d/?id=<YOUR-LICENSE-KEY>
